// Code generated by Icestudio 0.10

`default_nettype none

//---- Top entity
module main #(
 parameter v088e85 = 25
) (
 input v855bc5,
 output v73d28c,
 output [0:1] vinit
);
 localparam p1 = v088e85;
 wire w0;
 wire w2;
 assign w0 = v855bc5;
 assign v73d28c = w2;
 main_v8b1bc9 #(
  .target(p1)
 ) v8b1bc9 (
  .clk(w0),
  .new_clk(w2)
 );
 assign vinit = 2'b00;
endmodule


module main_v8b1bc9 #(
 parameter target = 0
) (
 input clk,
 output new_clk
);
 reg new_clk = 1'b0;
 // must have the required precision to hold
 // COUNT
 reg[31:0] tick_count = 0;
 
 parameter COUNT = (100000000 / target) / 2;
 
 always @(posedge clk)
     begin
         tick_count <= tick_count + 1;
         
         if (tick_count == COUNT - 1)
             begin
                 new_clk <= ~new_clk;
                 tick_count <= 0;
             end
     end
endmodule
